# Generated by Django 4.2.5 on 2023-10-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_contact_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default='2023-10-03'),
        ),
    ]
